"""PreToolUse hook: require explicit approval before editing protected files.

- pulse_hwm/cloud/updates/trust.py holds the update trust anchors; a change
  there is a security change (CLAUDE.md "Releases & update channel").
- installer/version.iss is generated by CI from pulse_hwm/__init__.py.

Returns permissionDecision "ask" so the user sees a prompt with the reason,
even in modes that would otherwise auto-approve the edit.
"""

from __future__ import annotations

import json
import sys

# Repo-relative paths (forward slashes) and why each one is protected.
PROTECTED_FILES = {
    "pulse_hwm/cloud/updates/trust.py": (
        "trust.py holds the update trust anchors (TRUSTED_UPDATE_KEYS, "
        "AUTHENTICODE_REQUIRED). This is a security change: run the full test "
        "suite and get reviewer eyes."
    ),
    "installer/version.iss": (
        "version.iss is generated by CI from pulse_hwm/__init__.py. Bump "
        "__version__ there instead."
    ),
}


def main() -> int:
    try:
        event = json.load(sys.stdin)
    except ValueError:
        return 0

    tool_input = event.get("tool_input", {})
    # Normalize Windows backslashes so matching works on any path form.
    file_path = (
        (tool_input.get("file_path") or tool_input.get("notebook_path") or "")
        .replace("\\", "/")
        .lower()
    )
    # Shell tools can write files too (sed -i, Set-Content, git checkout ...).
    # Commands can't be parsed reliably, so ANY command that mentions a
    # protected file asks first; a rare extra prompt beats a silent bypass.
    command = str(tool_input.get("command", "")).replace("\\", "/").lower()

    for protected, reason in PROTECTED_FILES.items():
        # Match the bare file name in commands: after a `cd`, a command can
        # refer to the file by a relative path such as just "trust.py".
        file_name = protected.rsplit("/", 1)[-1]
        if file_path.endswith(protected) or file_name in command:
            decision = {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "ask",
                    "permissionDecisionReason": f"Protected file: {reason}",
                }
            }
            print(json.dumps(decision))
            return 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
